server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost/springboot?serverTimezone=UTC
    username: root
    password: 123321
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate: 
      ddl-auto: create-drop
  cache:
    ehcache:
      config: classpath:ehcache.xml
#  security:
#    basic:
#      enabled: false

  liquibase: 
    enabled: true 
    change-log: classpath:/db/changelog/db.changelog-master.xml 
    
  
  

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 10111
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always



 